/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Spinner {
  interval: number
  frames: Array<string>
}
export interface Options {
  text?: string
  interval: number
  frames: string[]
  logWithoutTty: boolean
  enable: boolean
  hideCursor: boolean
  prefixText?: string
  suffixText?: string
}
export type Ora = OraBinding
export class OraBinding {
  isSpinning: boolean
  isTty: boolean
  constructor(options: Options)
  run(): void
  stop(): void
  pureWrite(text: string): void
  clear(): void
  updateText(text: string): void
  updateInterval(interval: number): void
  updateFrames(frames: Array<string>): void
}
